config/routes.rb
Rails.application.routes.draw do
  resources :customers
  get 'users/index'
  post 'users/import' => 'users#import', as: :import_users
  get 'users/profile/:id' => 'users#profile', as: :profile
  get 'users/edit/:id' => 'users#edit', as: :edit_user
  put 'users/update/:id' => 'users#update', as: :update_user

  resources :commission_reports do
    collection do
      post :import
      match 'search' => 'commission_reports#search', via: [:get, :post], as: :search
      post :calculate_all
      post :remove_negatives
      post :reset_all
    end
  end
  root 'main#index'

  devise_for :users
  
  
  resources :charts, only: [] do
    collection do
      get 'reports_by_markup'
      get 'reports_by_customer'
      get 'results_by_country'
      get 'competitions_by_year'
    end
  end

end

app/models/commission_report.rb
# == Schema Information
#
# Table name: commission_reports
#
#  id                 :integer          not null, primary key
#  employee_name      :string
#  customer_name      :string
#  account_manager_id :integer
#  recruiter_id       :integer
#  support_id         :integer
#  pay_rate           :decimal(, )
#  total_hours        :decimal(, )
#  total_gross_pay    :decimal(, )
#  total_bill         :decimal(, )
#  am_rate            :decimal(, )
#  rec_rate           :decimal(, )
#  sup_rate           :decimal(, )
#  mark_up            :decimal(, )
#  week_ending        :date
#  week_beginning     :date
#  revenue            :decimal(, )
#  am_amount          :decimal(, )
#  rec_amount         :decimal(, )
#  sup_amount         :decimal(, )
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  start_date         :date
#  double             :boolean          default(FALSE)
#

class CommissionReport < ActiveRecord::Base
  include ArelHelpers::ArelTable
  include ArelHelpers::JoinAssociation
  
  before_save :calculate
  belongs_to :customer
  belongs_to :account_manager, class_name: "User", foreign_key: "account_manager_id"
  belongs_to :recruiter, class_name: "User", foreign_key: "recruiter_id"
  belongs_to :support, class_name: "User", foreign_key: :support_id
  
  scope :current_week, -> { where(CommissionReport[:week_ending].eq( Date.current.end_of_week - 1.week)) }
  
  # IMPORT FROM CSV
  def self.assign_from_row(row)
    commission = CommissionReport.new(employee_name: row[:employee])
    w = Chronic.parse(row[:week_ending]).present? ? Chronic.parse(row[:week_ending]).end_of_week : Date.current.end_of_week - 1.week
    commission.assign_attributes row.to_hash.slice(:customer_name, :account_manager, :recruiter, :recruiting_support, :pay_rate, :total_hours, :total_gross_pay, :total_bill, :start_date)
    if row[:double].starts_with?("y")
      commission.double = true
    end
    commission.account_manager = User.find_or_create_by(username: row[:created_by], role: "Account Manager")
    commission.recruiter = User.find_or_create_by(username: row[:assigned_by], role: "Recruiter")
    commission.support = User.find_or_create_by(username: row[:serviced_by], role: "Recruiting Support")
    commission.customer = Customer.find_or_create_by(name: row[:customer_name])
    commission.week_ending = w
    commission
  end
  
  #  EXPORT TO CSV
  def self.to_csv
    attributes = %w{ customer_name employee_name total_hours total_bill total_gross_pay mark_up revenue profit am_amount rec_amount sup_amount start_date pay_rate}
    CSV.generate(headers: true) do |csv|
    csv << attributes
    
    all.each do |commission|
    csv << attributes.map{ |attr| commission.send(attr) }
      end
    end
  end
  
  def set_revenue
    self.revenue = total_bill - total_gross_pay
  end
  
  
  def self.calculate_all!
    all.each do |commission|
      commission.calculate
      commission.save
    end
  end
  
  def calculate
    set_revenue
    if recruiter.present? && recruiter.advanced?
      self.rec_rate = adv_recruiter_rate
    else
      self.rec_rate = recruiter_rate
    end
    
    if double?
      self.sup_rate = rec_support_rate * 2
    else
      self.sup_rate = rec_support_rate
    end
    self.am_rate = acct_manager_rate
    set_amounts
    self.week_beginning = week_ending.beginning_of_week
    self.mark_up = (total_bill / total_gross_pay).round(2)
    self.customer = Customer.find_or_create_by(name: customer_name)
  end

  def profit
    revenue / 2
  end

  def commission_total(rate)
    if profit.present? && rate.present?
      profit * rate
    else
      0
    end
  end


  def recruiter_rate
      if recruiter.present? && recruiter.house?
          0.02
      elsif recruiter.present? && recruiter.team?
          0.02
      elsif recruiter.present? && recruiter.lisa?
          0.05
      else
          case pay_rate
          when (0...9.99)
              0.025
          when (10...15.99)
              0.05
          when (16...21.99)
              0.075
          when (22...300)
              0.1
          end
      end
  end
  
  def rec_support_rate
      case pay_rate
      when (0..10.00)
        0.01
      when (10.01..12.00)
        0.02
      when (12.01..300)
        0.03
      end
  end
  
  def adv_recruiter_rate
      if recruiter.reports.current_week.sum(:total_hours) <= 1000
          case pay_rate
          when (0..15.99)
              0.075
          when (16..21.99)
              0.1
          when (22..30)
              0.125
          when (30..300)
              0.15
          end
      elsif recruiter.reports.current_week.sum(:total_hours) > 1000 && recruiter.reports.current_week.sum(:total_hours) < 1500
          case pay_rate
          when (0..15.99)
              0.1
          when (16..21.99)
              0.125
          when (22..30)
              0.15
          when (30..300)
              0.175
          end
      elsif recruiter.reports.current_week.sum(:total_hours) > 1501 && recruiter.reports.current_week.sum(:total_hours) < 2000
          case pay_rate
          when (0..15.99)
              0.125
          when (16..21.99)
              0.15
          when (22..30)
              0.175
          when (30..300)
              0.2
          end
      elsif recruiter.reports.current_week.sum(:total_hours) > 2000
          case pay_rate
          when (0..15.99)
              0.15
          when (16..21.99)
              0.175
          when (22..30)
              0.2
          when (30..300)
              0.2 # This will need changed
          end
      end
  end
  def special_rec_rate
      case pay_rate
      when (0...9.99)
          0.025
      when (10...15.99)
          0.05
      when (16...21.99)
          0.075
      when (22...300)
          0.1
      end
  end
  
  def acct_manager_rate
    # def acct_manager_rate(com_reports) # Feeling like this is how it should be... not sure.
    if account_manager.present?
      total_hrs = account_manager.reports.current_week.sum(:total_hours)
      # total_hrs = com_reports.sum(:total_hours)
      if account_manager.special?
          special_rec_rate
      elsif total_hrs < 1000
          0.025
      elsif total_hrs > 1000 && total_hrs < 2000
          0.03
      elsif total_hrs > 2000 && total_hrs < 3000
          0.035
      elsif total_hrs > 3000 && total_hrs < 4000
          0.04
      elsif total_hrs > 4000 && total_hrs < 5000
          0.045
      elsif total_hrs > 5000
          0.05
      else
          0.025
      end
    end
  end
  
  def set_amounts
    self.am_amount = commission_total(acct_manager_rate)
    self.sup_amount = commission_total(sup_rate)
    if recruiter.present? && recruiter.advanced
      self.rec_amount = commission_total(adv_recruiter_rate)
    else
      self.rec_amount = commission_total(recruiter_rate)
    end
  end
end

app/models/commission_report/import.rb
class CommissionReport::Import
    include ActiveModel::Model
    attr_accessor :file, :imported_count
    
    def process!
        @imported_count = 0
        CSV.foreach(file.path, headers: true, header_converters: :symbol) do |row|
            commission = CommissionReport.assign_from_row(row)
            if commission.save
                @imported_count += 1
            else
                errors.add(:base, "Line #{$.}  - #{commission.errors.full_messages.join(",")}")
            end
        end
    end
    
    def save
        process!
        errors.none?
    end
    
end

app/controllers/commission_reports_controller.rb
# == Schema Information
#
# Table name: commission_reports
#
#  id                 :integer          not null, primary key
#  employee_name      :string
#  customer_name      :string
#  account_manager_id :integer
#  recruiter_id       :integer
#  support_id         :integer
#  pay_rate           :decimal(, )
#  total_hours        :decimal(, )
#  total_gross_pay    :decimal(, )
#  total_bill         :decimal(, )
#  am_rate            :decimal(, )
#  rec_rate           :decimal(, )
#  sup_rate           :decimal(, )
#  mark_up            :decimal(, )
#  week_ending        :date
#  week_beginning     :date
#  revenue            :decimal(, )
#  am_amount          :decimal(, )
#  rec_amount         :decimal(, )
#  sup_amount         :decimal(, )
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  start_date         :date
#  double             :boolean          default(FALSE)
#

class CommissionReportsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_commission_report, only: [:show, :edit, :update, :destroy]

  # GET /commission_reports
  # GET /commission_reports.json
  def index
    @import  = CommissionReport::Import.new
    @q = CommissionReport.includes(:account_manager, :recruiter, :support, :customer).ransack(params[:q]) if current_user.admin?
    @q = current_user.reports.includes(:account_manager, :recruiter, :support, :customer).ransack(params[:q]) if !current_user.admin?
    @commission_reports = @q.result(distinct: true)
    @chart_reports = @q.result
    @week_ending = params[:week_ending]
    respond_to do |format|
      format.html
      format.csv { send_data @commission_reports.distinct.to_csv, filename: "#{current_user.name}-commissions-#{Time.current}.csv" }
    end 
  end
  
  def search
    # index
    @import  = CommissionReport::Import.new
    @week_ending = params[:week_ending]
    @q = CommissionReport.includes(:account_manager, :recruiter, :support, :customer).ransack(params[:q]) if current_user.admin?
    @q = current_user.reports.includes(:account_manager, :recruiter, :support, :customer).ransack(params[:q]) if !current_user.admin?
    @commission_reports = @q.result(distinct: true)
    @chart_reports = @q.result
    render :index
  end

  # GET /commission_reports/1
  # GET /commission_reports/1.json
  def show
  end

  # GET /commission_reports/new
  def new
    @commission_report = CommissionReport.new
  end
  
  def import
    @import  = CommissionReport::Import.new(commission_report_import_params)
    if @import.save
      redirect_to commission_reports_path, notice: "Imported #{@import_count} commissions."
    else
      flash[:alert] = "There were errors with your CSV file."
      render action: :index
    end
  end
  

  # GET /commission_reports/1/edit
  def edit
  end

  # POST /commission_reports
  # POST /commission_reports.json
  def create
    @commission_report = CommissionReport.new(commission_report_params)

    respond_to do |format|
      if @commission_report.save
        format.html { redirect_to @commission_report, notice: 'Commission report was successfully created.' }
        format.json { render :show, status: :created, location: @commission_report }
      else
        format.html { render :new }
        format.json { render json: @commission_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /commission_reports/1
  # PATCH/PUT /commission_reports/1.json
  def update
    respond_to do |format|
      if @commission_report.update(commission_report_params)
        format.html { redirect_to @commission_report, notice: 'Commission report was successfully updated.' }
        format.json { render :show, status: :ok, location: @commission_report }
      else
        format.html { render :edit }
        format.json { render json: @commission_report.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def reset_all
    CommissionReport.all.map(&:destroy)
    redirect_to commission_reports_path, notice: "Successfully deleted all commission records."
  end
  
  def calculate_all
    CommissionReport.all.map(&:save)
    # CommissionReport.calculate_all!
    redirect_to commission_reports_path, notice: "Successfully updated all commission records."
  end
  
  # DELETE /commission_reports/1
  # DELETE /commission_reports/1.json
  def destroy
    @commission_report.destroy
    respond_to do |format|
      format.html { redirect_to commission_reports_url, notice: 'Commission report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_commission_report
      @commission_report = CommissionReport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def commission_report_params
      params.require(:commission_report).permit(:employee_name, :customer_name, :account_manager_id, :recruiter_id, :support_id, 
                    :pay_rate, :total_hours, :total_gross_pay, :total_bill, :am_rate, :rec_rate, :sup_rate, :double,
                    :mark_up, :week_ending, :week_beginning, :revenue, :am_amount, :rec_amount, :sup_amount, :customer_id)
    end
    
    def commission_report_import_params
        params.require(:commission_report_import).permit(:file)
    end
end

app/helpers/commission_reports_helper.rb
# == Schema Information
#
# Table name: commission_reports
#
#  id                 :integer          not null, primary key
#  employee_name      :string
#  customer_name      :string
#  account_manager_id :integer
#  recruiter_id       :integer
#  support_id         :integer
#  pay_rate           :decimal(, )
#  total_hours        :decimal(, )
#  total_gross_pay    :decimal(, )
#  total_bill         :decimal(, )
#  am_rate            :decimal(, )
#  rec_rate           :decimal(, )
#  sup_rate           :decimal(, )
#  mark_up            :decimal(, )
#  week_ending        :date
#  week_beginning     :date
#  revenue            :decimal(, )
#  am_amount          :decimal(, )
#  rec_amount         :decimal(, )
#  sup_amount         :decimal(, )
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  start_date         :date
#  double             :boolean          default(FALSE)
#

module CommissionReportsHelper
end

app/views/commission_reports/_form.html.erb
<%= simple_form_for(@commission_report) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :employee_name %>
    <%= f.input :customer_name %>
    <%= f.association :account_manager, collection: User.account_managers %>
    <%= f.association :recruiter, collection: User.recruiters %>
    <%= f.association :support, collection: User.support %>
    <%= f.input :double %>
    <%= f.input :pay_rate %>
    <%= f.input :total_hours %>
    <%= f.input :total_gross_pay %>
    <%= f.input :total_bill %>
    <%= f.input :am_rate %>
    <%= f.input :rec_rate %>
    <%= f.input :sup_rate %>
    <%= f.input :mark_up %>
    <%= f.input :week_ending %>
    <%= f.input :week_beginning %>
    <%= f.input :revenue %>
    <%= f.input :am_amount %>
    <%= f.input :rec_amount %>
    <%= f.input :sup_amount %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/commission_reports/_import_form.html.erb
<div class="col-md-6 well">
  <%= form_for @import, url: import_commission_reports_path, multipart: true do |f| %>
  <h4 class="bold text-center">Import Commissions as CSV</h4>
   	 <hr>	
  	<% if @import.errors.any? %>
  <div class='alert alert-error'>
  		<% @import.errors.full_messages.each do |msg| %>
  			<div><%= msg %></div>
  		<% end %>
  </div>
  <% end %>
  <div class="form-group">
  	<%= f.file_field :file %>
  	<%= f.submit "Upload" %>
  </div>
  <% end %>
</div>

app/views/commission_reports/_search.html.erb
<div class="text-center form-inline">
<%= search_form_for @q, url: search_commission_reports_path,
                        html: { method: :post } do |f| %>
  <%= f.input :week_ending_eq, label: false, input_html: {value: Date.current.end_of_week - 1.week}, class: "form-control" %>
  <%= f.input :employee_name_cont, label: false, class: "form-control", placeholder: "Employee Name" %>
  <%= f.input :customer_name_start, label: false, class: "form-control", placeholder: "Customer Name"  %>

  <%= f.input :recruiter_username_or_recruiter_first_name_or_recruiter_last_name_cont, label: false, class: "form-control", placeholder: "Recruiter Name"  %>


  <%= f.submit %>
<% end %>
</div>

app/views/commission_reports/_table.html.erb
<% if @user.present? %>
<%= render "commission_reports/tables/acct_mgr", commission_reports: commission_reports if @user.account_manager? %>
<%= render "commission_reports/tables/rec", commission_reports: commission_reports if @user.recruiter? %>
<%= render "commission_reports/tables/sup", commission_reports: commission_reports if @user.recruiting_support? %>
<%= render "commission_reports/tables/table", commission_reports: commission_reports if @user.admin? %>
<% else %>
<%= render "commission_reports/tables/table", commission_reports: commission_reports %>
<% end %>

app/views/commission_reports/edit.html.erb
<h1>Editing Commission Report</h1>

<%= render 'form' %>

<%= link_to 'Show', @commission_report %> |
<%= link_to 'Back', commission_reports_path %>

app/views/commission_reports/index.html.erb
<%= link_to "Export Commission Reports", commission_reports_path(format: :csv), class: "btn btn-default"  if current_user.admin?  %>
<%= link_to "Delete All", reset_all_commission_reports_path, method: :post, data: {confirm: 'Are you sure you want to delete all commission reports?', disable_with: 'Deleting all commissions...' }, class: "btn btn-default" if current_user.admin? %>
<hr>
<%= render "import_form" if current_user.admin?  %>
<%= link_to 'New Commission report', new_commission_report_path, class: "btn btn-default" if current_user.admin? %>
<%= link_to 'Recalculate All', calculate_all_commission_reports_path, method: :post, data: { disable_with: 'Updating all commissions...' }, class: "btn btn-default"  if current_user.admin?  %>
<div class="col-md-12 well">
  <%= render "search" %>
  <hr>
  <%= link_to "Clear", commission_reports_path, class: "btn btn-danger btn-lg pull-right" %>
</div>


<div class="col-md-12 well scroll">
  <h1> Commission Reports <span class="pull-right text-muted"><h1><%= @week_ending ? @week_ending : "Showing All Commissions" %></h1></span></h1>
  <%= render "commission_reports/table", commission_reports: @commission_reports %>
</div>


<div class="col-md-12 well">
  
  <h2>Commissions by Mark-Up</h2>
  <%= pie_chart @chart_reports.count, xtitle: "Mark-Up", ytitle: "Placements" %>
</div>

app/views/commission_reports/new.html.erb
<h1>New Commission Report</h1>

<%= render 'form' %>

<%= link_to 'Back', commission_reports_path %>

app/views/commission_reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Employee name:</strong>
  <%= @commission_report.employee_name %>
</p>

<p>
  <strong>Customer name:</strong>
  <%= @commission_report.customer_name %>
</p>

<p>
  <strong>Account manager:</strong>
  <%= @commission_report.account_manager_id %>
</p>

<p>
  <strong>Recruiter:</strong>
  <%= @commission_report.recruiter_id %>
</p>

<p>
  <strong>Support:</strong>
  <%= @commission_report.support_id %>
</p>

<p>
  <strong>Pay rate:</strong>
  <%= @commission_report.pay_rate %>
</p>

<p>
  <strong>Total hours:</strong>
  <%= @commission_report.total_hours %>
</p>

<p>
  <strong>Total gross pay:</strong>
  <%= @commission_report.total_gross_pay %>
</p>

<p>
  <strong>Total bill:</strong>
  <%= @commission_report.total_bill %>
</p>

<p>
  <strong>Am rate:</strong>
  <%= @commission_report.am_rate %>
</p>

<p>
  <strong>Rec rate:</strong>
  <%= @commission_report.rec_rate %>
</p>

<p>
  <strong>Sup rate:</strong>
  <%= @commission_report.sup_rate %>
</p>

<p>
  <strong>Mark up:</strong>
  <%= @commission_report.mark_up %>
</p>

<p>
  <strong>Week ending:</strong>
  <%= @commission_report.week_ending %>
</p>

<p>
  <strong>Week beginning:</strong>
  <%= @commission_report.week_beginning %>
</p>

<p>
  <strong>Revenue:</strong>
  <%= @commission_report.revenue %>
</p>

<p>
  <strong>Am amount:</strong>
  <%= @commission_report.am_amount %>
</p>

<p>
  <strong>Rec amount:</strong>
  <%= @commission_report.rec_amount %>
</p>

<p>
  <strong>Sup amount:</strong>
  <%= @commission_report.sup_amount %>
</p>

<%= link_to 'Edit', edit_commission_report_path(@commission_report) %> |
<%= link_to 'Back', commission_reports_path %>