config/routes.rb
Rails.application.routes.draw do
  resources :customers
  get 'users/index'
  post 'users/import' => 'users#import', as: :import_users
  get 'users/profile/:id' => 'users#profile', as: :profile
  get 'users/edit/:id' => 'users#edit', as: :edit_user
  put 'users/update/:id' => 'users#update', as: :update_user

  resources :commission_reports do
    collection do
      post :import
      match 'search' => 'commission_reports#search', via: [:get, :post], as: :search
      post :calculate_all
      post :remove_negatives
      post :reset_all
    end
  end
  root 'main#index'

  devise_for :users
  
  
  resources :charts, only: [] do
    collection do
      get 'reports_by_markup'
      get 'reports_by_customer'
      get 'results_by_country'
      get 'competitions_by_year'
    end
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  first_name             :string
#  last_name              :string
#  username               :string
#  role                   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  advanced               :boolean          default(FALSE)
#  multi_rates            :boolean          default(FALSE)
#

class User < ActiveRecord::Base
  include ArelHelpers::ArelTable
  include ArelHelpers::JoinAssociation
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  scope :account_managers, -> { where(User[:role].eq("Account Manager")) }
  scope :recruiters, -> { where(User[:role].eq("Recruiter").and(User[:username].not_eq("South").or(User[:username].not_eq("North").or(User[:username].not_eq("NorthWest"))))) }
  scope :support, -> { where(User[:role].eq("Recruiting Support")) }
  scope :admin, -> { where(User[:role].eq("Admin")) }

  def account_manager?; role == "Account Manager"; end
  def admin?; role == "Admin"; end
  def recruiter?; role == "Recruiter"; end
  def jonna?; username == "JonnaD"; end
  def lisa?; username == "LisaS"; end
  def house?; first_name == "House"; end
  def recruiting_support?; role == "Recruiting Support"; end

  def name
    first_name && last_name ? "#{first_name} #{last_name}" : username
  end
  
  def team?
    case username
    when "South"
        true
    when "North"
        true
    when "Sandusky"
        true
    else
        false
    end
  end
  
  def special?
    case username
    when "JonnaD"
        true
    when "JustinB"
        true
    when "BTowner"
        true
    when "KristenM"
        true
    when "ZacharyP"
        true
    else
        false
    end
  end
  
  # IMPORT FROM CSV
  def self.assign_from_row(row)
    user = User.new(email: row[:email], password: "111111", password_confirmation: "111111")
    user.assign_attributes row.to_hash.slice(:first_name, :last_name, :username, :role, :email)
    user.advanced = row[:advanced].starts_with?("y") ? true : false
    user
  end

  #  EXPORT TO CSV
  def self.to_csv
    attributes = %w{ first_name last_name name email username role }
    CSV.generate(headers: true) do |csv|
    csv << attributes
    
    all.each do |user|
    csv << attributes.map{ |attr| user.send(attr) }
      end
    end
  end
  
  def reports
    if account_manager?
      CommissionReport.includes(:account_manager, :recruiter, :support, :customer).where(account_manager_id: id)
    elsif recruiter?
      CommissionReport.includes(:account_manager, :recruiter, :support, :customer).where(recruiter_id: id)
    elsif recruiting_support?
      CommissionReport.includes(:account_manager, :recruiter, :support, :customer).where(support_id: id)
    else
      CommissionReport.none
    end
  end
  
  def customers
    if account_manager?
      Customer.joins(:commission_reports).where(CommissionReport[:account_manager_id].eq(id))
    elsif recruiter?
      Customer.joins(:commission_reports).where(CommissionReport[:recruiter_id].eq(id))
    elsif recruiting_support?
      Customer.joins(:commission_reports).where(CommissionReport[:support_id].eq(id))
    else
      Customer.none
    end
  end
  
  def current_report
    reports.current_week.last
  end
  
  def total_commission_amt(com_reports)
    case role
    when "Account Manager"
      com_reports.sum(:am_amount)
    when "Recruiter"
      com_reports.sum(:rec_amount)
    when "Recruiting Support"
      com_reports.sum(:sup_amount)
    end
  end
  
  def total_revenue(com_reports)
      com_reports.sum(:revenue)
  end
  def total_hours(com_reports)
      com_reports.sum(:total_hours)
  end
  def total_profit(com_reports)
      total_revenue(com_reports) / 2
  end
  
  def last_commission_week
    if reports.order(:week_ending).last.present?
      reports.order(:week_ending).last.week_ending.stamp("12/18/1989")
    else
      "No Records Found"
    end
  end
  
end

app/models/user/import.rb
class User::Import
    include ActiveModel::Model
    attr_accessor :file, :imported_count
    
    def process!
        @imported_count = 0
        CSV.foreach(file.path, headers: true, header_converters: :symbol) do |row|
            commission = User.assign_from_row(row)
            if commission.save
                @imported_count += 1
            else
                errors.add(:base, "Line #{$.}  - #{commission.errors.full_messages.join(",")}")
            end
        end
    end
    
    def save
        process!
        errors.none?
    end
    
end

app/controllers/users_controller.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  first_name             :string
#  last_name              :string
#  username               :string
#  role                   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  advanced               :boolean          default(FALSE)
#  multi_rates            :boolean          default(FALSE)
#

class UsersController < ApplicationController
  def index
    @import  = User::Import.new
    @users = User.all
    respond_to do |format|
      format.html
      format.csv { send_data @users.distinct.to_csv, filename: "users-export-#{Time.current}.csv" }
    end 
  end
  
  def import
    @import  = User::Import.new(user_import_params)
    if @import.save
      redirect_to users_index_path, notice: "Imported #{@import_count} commissions."
    else
      flash[:alert] = "There were errors with your CSV file."
      render action: :index
    end
    
  end

  def profile
    @user = User.find(params[:id])
    @customers = @user.customers
    @commission_reports = @user.reports if !@user.admin?
    @commission_reports = CommissionReport.includes(:account_manager, :recruiter, :support, :customer).all if @user.admin?
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to profile_path(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def user_import_params
      params.require(:user_import).permit(:file)
  end
  def user_params
      params.require(:user).permit(:first_name, :last_name, :username, :email, :role, :advanced)
  end
end

app/helpers/users_helper.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  first_name             :string
#  last_name              :string
#  username               :string
#  role                   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  advanced               :boolean          default(FALSE)
#  multi_rates            :boolean          default(FALSE)
#

module UsersHelper
end

app/views/users/_import_form.html.erb
<%= form_for @import, url: import_users_path, multipart: true do |f| %>
  
  <h4 class="bold text-info">Import Users as CSV</h4>
   	 <hr>	
  	<% if @import.errors.any? %>
  <div class='alert alert-error'>
  		<% @import.errors.full_messages.each do |msg| %>
  			<div><%= msg %></div>
  		<% end %>
  </div>
  <% end %>
  <div class="form-group">
  	<%= f.file_field :file %>
  	<%= f.submit "Upload" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h2>Edit <%= @user.name %></h2>

<%= simple_form_for(@user, url: update_user_path(@user), html: { method: :put }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :first_name, required: true, autofocus: true %>
    <%= f.input :last_name, required: true %>
    <%= f.input :email, required: true %>
    <%= f.input :advanced if @user.recruiter? %>
    <%= f.input :role, include_blank: false, required: true, collection: ["Recruiter", "Account Manager", "Support", "Admin"], prompt: "Choose your role" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Update" %>
  </div>
<% end %>

app/views/users/index.html.erb
<h2 class="page-header text-center">All Users</h2>
<div class="col-md-12 well">
  <%= render "import_form"  %>
</div>


<hr>
  <div class="col-md-4 well">
    <h2>Account Managers</h2>
    <ul class="list-group">
    <% User.account_managers.order(:username).each do |user| %>
      <%= link_to profile_path(user), class: "list-link" do %>
        <li class="list-group-item <%= user.advanced ? "list-group-item-success" : "list-group-item-info"%>"><%= user.id %> --- <%= user.name %> <span class="pull-right"><%= user.username %></span></li>
      <% end %>
    <% end %>
    </ul>
  </div>
  <div class="col-md-4 well">
    <h2>Recruiters</h2>
    <ul class="list-group">
    <% User.recruiters.order(:username).each do |user| %>
      <%= link_to profile_path(user), class: "list-link" do %>
        <li class="list-group-item <%= user.advanced ? "list-group-item-success" : "list-group-item-info"%>"><%= user.id %> --- <%= user.name %> <span class="pull-right"><%= user.username %></span></li>
      <% end %>
    <% end %>
    </ul>
  </div>
  <div class="col-md-4 well">
    <h2>Recruiting Supports</h2>
    <ul class="list-group">
    <% User.support.order(:username).each do |user| %>
      <%= link_to profile_path(user), class: "list-link" do %>
        <li class="list-group-item <%= user.advanced ? "list-group-item-success" : "list-group-item-info"%>"><%= user.id %> --- <%= user.name %> <span class="pull-right"><%= user.username %></span></li>
      <% end %>
    <% end %>
    </ul>
  </div>
  <div class="col-md-4 well">
    <h2> Admin</h2>
    <ul class="list-group">
    <% User.order(:username).admin.each do |user| %>
      <%= link_to profile_path(user), class: "list-link" do %>
        <li class="list-group-item"><%= user.id %> --- <%= user.name %> <span class="pull-right"><%= user.username %></span></li>
      <% end %>
    <% end %>
    </ul>
  </div>

app/views/users/profile.html.erb
<h1><%= @user.name %> <small> <%= @user.role %></small></h1>
<h3><%= @user.email %></h3>
<h3><%= @user.last_commission_week %></h3>
<div class="col-md-4"><h2>Commission: <%= number_to_currency @user.total_commission_amt(@commission_reports.current_week) %></h2></div>
<div class="col-md-4"><h2>Hours: <%= number_with_delimiter(@user.total_hours(@commission_reports.current_week), delimiter: ",") %></h2></div>
<div class="col-md-4"><h2>Revenue: <%= number_to_currency @user.total_revenue(@commission_reports.current_week) %></h2></div>
<%= link_to "Edit", edit_user_path(@user), class: "btn btn-default" %>
<div class="col-md-12 well table-responsive scroll800">
  <%= render "commission_reports/table", commission_reports: @commission_reports.order(:employee_name) %>
</div>
<div class="col-md-12 well">
  <h2>By Mark Up</h2>
  <%= column_chart @commission_reports.order(:mark_up).group(:mark_up).count, xtitle: "Mark-Up", ytitle: "Placements" %>
</div>
<div class="col-md-12 well">
  <h2>Placements By Company</h2>
  <%= column_chart @commission_reports.group(:customer_name).count, xtitle: "Customer", ytitle: "Placements" %>
</div>

<div class="col-md-12 well">
  <h2>By Pay Rate</h2>
  <%= column_chart @commission_reports.order(:pay_rate).group(:pay_rate).count, xtitle: "Pay Rate", ytitle: "Placements" %>
</div>