config/routes.rb
Rails.application.routes.draw do
  resources :customers
  get 'users/index'
  post 'users/import' => 'users#import', as: :import_users
  get 'users/profile/:id' => 'users#profile', as: :profile
  get 'users/edit/:id' => 'users#edit', as: :edit_user
  put 'users/update/:id' => 'users#update', as: :update_user

  resources :commission_reports do
    collection do
      post :import
      match 'search' => 'commission_reports#search', via: [:get, :post], as: :search
      post :calculate_all
      post :remove_negatives
      post :reset_all
    end
  end
  root 'main#index'

  devise_for :users
  
  
  resources :charts, only: [] do
    collection do
      get 'reports_by_markup'
      get 'reports_by_customer'
      get 'results_by_country'
      get 'competitions_by_year'
    end
  end

end

app/models/customer.rb
# == Schema Information
#
# Table name: customers
#
#  id         :integer          not null, primary key
#  name       :string
#  address    :string
#  state      :string
#  zipcode    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Customer < ActiveRecord::Base
  has_many :commission_reports
  
  def total_bill(week_ending)
    week = Chronic.parse(week_ending)
    commission_reports.where(week_ending: week).sum(:total_bill)
  end
  
  def account_manager
    commission_reports.last.account_manager if commission_reports.any?
  end
  
  def total_rev
    commission_reports.sum(:revenue)
  end
  
end

app/controllers/customers_controller.rb
# == Schema Information
#
# Table name: customers
#
#  id         :integer          not null, primary key
#  name       :string
#  address    :string
#  state      :string
#  zipcode    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CustomersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.includes(:commission_reports).all if current_user.admin?
    @customers = current_user.customers.distinct.order(:name) if !current_user.admin?
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name, :address, :state, :zipcode)
    end
end

app/helpers/customers_helper.rb
# == Schema Information
#
# Table name: customers
#
#  id         :integer          not null, primary key
#  name       :string
#  address    :string
#  state      :string
#  zipcode    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

module CustomersHelper
end

app/views/customers/_form.html.erb
<%= simple_form_for(@customer) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :state %>
    <%= f.input :zipcode %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<h1>All Customers</h1>
<div class="text-right"><%= link_to 'New Customer', new_customer_path, class: "btn btn-default" %>
  
</div>
<hr>
<div class="col-md-12 table-responsive scroll">
  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Current Billing</th>
        <th colspan="2"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @customers.each do |customer| %>
        <tr>
          <td><%=link_to customer.name, customer %></td>
          <td><% if customer.account_manager.present? %> <%= link_to customer.account_manager.name, profile_path(customer.account_manager) %><% else %><%= customer.commission_reports.any? ? "Unassigned" : "Inactive" %> <% end %> </td>
          <td><%= number_to_currency(customer.total_bill(Date.today.end_of_week - 1.week)) %></td>
          <td></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<h1>
  <strong>Name:</strong>
  <%= @customer.name %>
</h1>

<p>
  <strong>Address:</strong><br>
  <%= @customer.address %>
  CITY, <%= @customer.state %> <%= @customer.zipcode %>
</p>
<div class="col-md-6">
  <%= pie_chart @customer.commission_reports.order(:mark_up).group(:mark_up).count %>
</div>
<h3>Total Bill: <%= number_to_currency(@customer.total_bill(Date.today.end_of_week - 1.week)) %></h3>
<%= link_to 'Edit', edit_customer_path(@customer) %> <%= link_to 'Destroy', @customer, method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Back', customers_path %>

<div class="col-md-10">
  <%= render "commission_reports/table", commission_reports: @customer.commission_reports %>
</div>