config/routes.rb
Rails.application.routes.draw do
  resources :customers
  get 'users/index'
  post 'users/import' => 'users#import', as: :import_users
  get 'users/profile/:id' => 'users#profile', as: :profile
  get 'users/edit/:id' => 'users#edit', as: :edit_user
  put 'users/update/:id' => 'users#update', as: :update_user

  resources :commission_reports do
    collection do
      post :import
      match 'search' => 'commission_reports#search', via: [:get, :post], as: :search
      post :calculate_all
      post :remove_negatives
      post :reset_all
    end
  end
  root 'main#index'

  devise_for :users
  
  
  resources :charts, only: [] do
    collection do
      get 'reports_by_markup'
      get 'reports_by_customer'
      get 'results_by_country'
      get 'competitions_by_year'
    end
  end

end

app/views/layouts/_alert.html.erb
<p class="alert"><%= alert %></p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "GTR Commissions", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
        <% if user_signed_in? %>
        <ul class="nav navbar-nav">
          <li><%= link_to "<span data-toggle='tooltip' data-placement='bottom' title='View Profile'>#{current_user.username}</span>".html_safe, profile_path(current_user) if user_signed_in? %></li>
          <li><%= link_to "Customers", customers_path %></li>
          <li><%= link_to "Commission Reports", commission_reports_path %></li>
          <% if current_user.admin? %>
          <li><%= link_to "Users", users_index_path  %></li>
          <%= render "layouts/dropdowns/account_manager" %>
          <%= render "layouts/dropdowns/recruiter" %>
          <%= render "layouts/dropdowns/support" %>
          <%= render "layouts/dropdowns/admin" %>
          <% end %>
        </ul>
        
        <% else %>
        <ul class="nav navbar-nav">
          <li><%= link_to "SIGN IN", new_user_session_path(redirect_to: request.path) %></li>
          <li><%= link_to "SIGN UP", new_user_registration_path %></li>
        </ul>
        <% end %>
        
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "<i class='fa fa-power-off fa-lg'></i>".html_safe, destroy_user_session_path, method: :delete if user_signed_in? %></li>
      </ul>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_notice.html.erb
<p class="notice"><%= notice %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workspace</title>
    <%= javascript_include_tag "https://www.google.com/jsapi" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
  
    <%= render "layouts/navbar" %>
    <%= link_to "<i class='fa fa-arrow-left fa-lg' data-toggle='tooltip' data-placement='bottom' title='BACK'></i>".html_safe, :back, class: "navbar-brand back-btn" if user_signed_in? %>
    <%= render "layouts/alert" if alert %>
    <%= render "layouts/notice" if notice %>
    
    <div class="container-fluid">
      <%= yield %>
    </div>
  
  </body>
</html>